apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-edb-bvk
  namespace: "jobs"
spec:
  schedule: "0 8/12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: check-edb-bvk
            image: ognjenit/edb-bvk:0.0.3
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - python3 /app/lambda_function.py
            env:
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASSWORD
          restartPolicy: OnFailure
